/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkOrdersRouteImport } from './routes/work-orders'
import { Route as SettingsTeamRouteImport } from './routes/settings.team'
import { Route as WorkOrdersWorkOrderIdRouteImport } from './routes/work-orders.$workOrderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkOrdersRoute = WorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTeamRoute = SettingsTeamRouteImport.update({
  id: '/settings/team',
  path: '/settings/team',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkOrdersWorkOrderIdRoute = WorkOrdersWorkOrderIdRouteImport.update({
  id: '/$workOrderId',
  path: '/$workOrderId',
  getParentRoute: () => WorkOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/work-orders': typeof WorkOrdersRouteWithChildren
  '/settings/team': typeof SettingsTeamRoute
  '/work-orders/$workOrderId': typeof WorkOrdersWorkOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/work-orders': typeof WorkOrdersRouteWithChildren
  '/settings/team': typeof SettingsTeamRoute
  '/work-orders/$workOrderId': typeof WorkOrdersWorkOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/work-orders': typeof WorkOrdersRouteWithChildren
  '/settings/team': typeof SettingsTeamRoute
  '/work-orders/$workOrderId': typeof WorkOrdersWorkOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/work-orders' | '/settings/team' | '/work-orders/$workOrderId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/work-orders' | '/settings/team' | '/work-orders/$workOrderId'
  id:
    | '__root__'
    | '/'
    | '/work-orders'
    | '/settings/team'
    | '/work-orders/$workOrderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkOrdersRoute: typeof WorkOrdersRouteWithChildren
  SettingsTeamRoute: typeof SettingsTeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-orders': {
      id: '/work-orders'
      path: '/work-orders'
      fullPath: '/work-orders'
      preLoaderRoute: typeof WorkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/team': {
      id: '/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof SettingsTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-orders/$workOrderId': {
      id: '/work-orders/$workOrderId'
      path: '/$workOrderId'
      fullPath: '/work-orders/$workOrderId'
      preLoaderRoute: typeof WorkOrdersWorkOrderIdRouteImport
      parentRoute: typeof WorkOrdersRoute
    }
  }
}

interface WorkOrdersRouteChildren {
  WorkOrdersWorkOrderIdRoute: typeof WorkOrdersWorkOrderIdRoute
}

const WorkOrdersRouteChildren: WorkOrdersRouteChildren = {
  WorkOrdersWorkOrderIdRoute: WorkOrdersWorkOrderIdRoute,
}

const WorkOrdersRouteWithChildren = WorkOrdersRoute._addFileChildren(
  WorkOrdersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkOrdersRoute: WorkOrdersRouteWithChildren,
  SettingsTeamRoute: SettingsTeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
